In [3]:
## creating array using numpy
## creae 1D array
import numpy as np
arr1 = np.array([1,3,5,6,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 3 5 6 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 1D array
arr2 = np.array([1,3,5,6,5])
arr2.reshape((1,5))
# print(arr2.shape)

(1, 5)

In [17]:
## creating the 2d array
arr2 = np.array([[1,3,5,7,9,5],[3,4,5,3,3,3]])
print(arr2.shape)
print(arr2)

(2, 6)
[[1 3 5 7 9 5]
 [3 4 5 3 3 3]]


In [19]:
## inbuilt method to create the array
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
## ones methode 
np.ones((2,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
#### creating the identiy array
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimention : ", arr.ndim)
print("Size of the elements", arr.shape)
print("Data type", arr.dtype)
print("Item Size (in bytes)", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimention :  2
Size of the elements (2, 3)
Data type int64
Item Size (in bytes) 8
